// Export utilities for multiple formats
import type { DataRow } from '../types';

// Export to CSV
export const exportToCSV = (
  data: DataRow[],
  filename: string = 'export.csv'
): void => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0] || {});
  const csvContent = [
    headers.map((h) => `"${h}"`).join(','),
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header];
          if (value === null || value === undefined) return '""';
          const strValue = String(value);
          return `"${strValue.replace(/"/g, '""')}"`;
        })
        .join(',')
    ),
  ].join('\n');

  downloadFile(csvContent, filename, 'text/csv');
};

// Export to JSON
export const exportToJSON = (
  data: DataRow[],
  filename: string = 'export.json'
): void => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(jsonContent, filename, 'application/json');
};

// Export to HTML Table
export const exportToHTML = (
  data: DataRow[],
  filename: string = 'export.html',
  title: string = 'Data Export'
): void => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0] || {});
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      background-color: #f5f5f5;
    }
    h1 {
      color: #333;
    }
    table {
      border-collapse: collapse;
      width: 100%;
      background-color: white;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    th {
      background-color: #2563eb;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: bold;
      border-bottom: 2px solid #1e40af;
    }
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #ddd;
    }
    tr:hover {
      background-color: #f9fafb;
    }
    .footer {
      margin-top: 20px;
      font-size: 12px;
      color: #666;
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p>Generated on ${new Date().toLocaleString()}</p>
  <p>Total Records: <strong>${data.length}</strong></p>
  
  <table>
    <thead>
      <tr>
        ${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${data
        .map(
          (row) =>
            `<tr>
        ${headers.map((h) => `<td>${escapeHtml(String(row[h] || ''))}</td>`).join('')}
      </tr>`
        )
        .join('')}
    </tbody>
  </table>
  
  <div class="footer">
    <p>Data export generated by AutoInsight Data Analyzer</p>
  </div>
</body>
</html>
  `;

  downloadFile(htmlContent, filename, 'text/html');
};

// Export with statistics
export const exportWithStats = (
  data: DataRow[],
  filename: string = 'export_with_stats.json'
): void => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0] || {});
  const stats: Record<string, any> = {
    metadata: {
      exportDate: new Date().toISOString(),
      totalRows: data.length,
      totalColumns: headers.length,
    },
    data: data,
    columnStats: {},
  };

  // Calculate stats for each column
  headers.forEach((header) => {
    const values = data.map((row) => row[header]);
    const nonNull = values.filter((v) => v !== null && v !== undefined);
    const unique = new Set(nonNull.map((v) => String(v))).size;

    stats.columnStats[header] = {
      type: typeof nonNull[0],
      nonNull: nonNull.length,
      null: values.length - nonNull.length,
      unique: unique,
      missing: values.length - nonNull.length,
    };

    // If numeric, add more stats
    const numericValues = nonNull.filter((v) => !isNaN(Number(v))).map(Number);
    if (numericValues.length > 0) {
      const mean = numericValues.reduce((a, b) => a + b) / numericValues.length;
      stats.columnStats[header] = {
        ...stats.columnStats[header],
        min: Math.min(...numericValues),
        max: Math.max(...numericValues),
        mean: Math.round(mean * 100) / 100,
      };
    }
  });

  downloadFile(JSON.stringify(stats, null, 2), filename, 'application/json');
};

// Export comparison (side by side)
export const exportComparison = (
  originalData: DataRow[],
  cleanedData: DataRow[],
  filename: string = 'comparison.json'
): void => {
  const comparison = {
    metadata: {
      exportDate: new Date().toISOString(),
      originalRows: originalData.length,
      cleanedRows: cleanedData.length,
      rowsRemoved: originalData.length - cleanedData.length,
      removalPercentage: Math.round(
        ((originalData.length - cleanedData.length) / originalData.length) * 100
      ),
    },
    original: {
      data: originalData,
      sample: originalData.slice(0, 10),
    },
    cleaned: {
      data: cleanedData,
      sample: cleanedData.slice(0, 10),
    },
  };

  downloadFile(JSON.stringify(comparison, null, 2), filename, 'application/json');
};

// Generic file download helper
const downloadFile = (
  content: string,
  filename: string,
  mimeType: string
): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Escape HTML special characters
const escapeHtml = (text: string): string => {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
};

// Generate report with insights
export const generateAnalysisReport = (
  originalData: DataRow[],
  cleanedData: DataRow[],
  insights: string[],
  filename: string = 'analysis_report.html'
): void => {
  const removedRows = originalData.length - cleanedData.length;
  const removalRate = ((removedRows / originalData.length) * 100).toFixed(1);

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Data Analysis Report</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 20px;
      min-height: 100vh;
    }
    
    .container {
      max-width: 1000px;
      margin: 0 auto;
      background: white;
      border-radius: 10px;
      box-shadow: 0 10px 40px rgba(0,0,0,0.2);
      padding: 40px;
    }
    
    .header {
      border-bottom: 3px solid #667eea;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .header h1 {
      color: #333;
      font-size: 28px;
      margin-bottom: 5px;
    }
    
    .header p {
      color: #666;
      font-size: 14px;
    }
    
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin: 30px 0;
    }
    
    .stat-card {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    
    .stat-card h3 {
      font-size: 14px;
      opacity: 0.9;
      margin-bottom: 10px;
      text-transform: uppercase;
    }
    
    .stat-card .value {
      font-size: 32px;
      font-weight: bold;
    }
    
    .section {
      margin: 30px 0;
      padding: 20px;
      background: #f9fafb;
      border-left: 4px solid #667eea;
      border-radius: 4px;
    }
    
    .section h2 {
      color: #333;
      margin-bottom: 15px;
      font-size: 20px;
    }
    
    .insight-list {
      list-style: none;
    }
    
    .insight-list li {
      padding: 10px 0;
      border-bottom: 1px solid #ddd;
      color: #555;
    }
    
    .insight-list li:before {
      content: "✓ ";
      color: #10b981;
      font-weight: bold;
      margin-right: 8px;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      color: #666;
      font-size: 12px;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Data Analysis Report</h1>
      <p>Generated on ${new Date().toLocaleString()}</p>
    </div>
    
    <div class="stats-grid">
      <div class="stat-card">
        <h3>Original Rows</h3>
        <div class="value">${originalData.length}</div>
      </div>
      <div class="stat-card">
        <h3>Cleaned Rows</h3>
        <div class="value">${cleanedData.length}</div>
      </div>
      <div class="stat-card">
        <h3>Rows Removed</h3>
        <div class="value">${removedRows}</div>
      </div>
      <div class="stat-card">
        <h3>Removal Rate</h3>
        <div class="value">${removalRate}%</div>
      </div>
    </div>
    
    <div class="section">
      <h2>🎯 Key Insights</h2>
      <ul class="insight-list">
        ${insights.map((insight) => `<li>${insight}</li>`).join('')}
      </ul>
    </div>
    
    <div class="footer">
      <p>This report was generated by AutoInsight Data Analyzer</p>
      <p>For detailed data, please export the full dataset separately</p>
    </div>
  </div>
</body>
</html>
  `;

  downloadFile(htmlContent, filename, 'text/html');
};
